const vegtables = [
  'Bok Choy',
  'Snake Beans',
  'Sorrel Leaves',
  'Rocket Leaves',
  'Drumstick',
  'Cherry Tomatoes',
  'Kaffir Lime',
  'Plantain',
  'Turnip',
  'Sweet Potatoes',
  'Round Gourd',
  'Ridge Gourd',
  'Pimiento',
  'Spinach',
  'Onion',
  'Mustard Leaves',
  'Mushroom',
  'Radish',
  'Shallots',
  'Lettuce',
  'Leek',
  'Pumpkin',
  'Yam',
  'Jalapeno',
  'Jackfruit',
  'Horseradish',
  'Spring Onion',
  'Green Peas',
  'Green Chillies',
  'Cluster Beans',
  'Gherkins',
  'Garlic',
  'French Beans',
  'Fenugreek',
  'Cucumber',
  'Zucchini',
  'Corn',
  'Shiitake Mushroom',
  'Celery',
  'Cauliflower',
  'Carrot',
  'Capsicum',
  'Capers',
  'Broccoli',
  'Broad Beans',
  'Bottle Gourd',
  'Bitter Gourd',
  'Lady Finger',
  'Lotus Stem',
  'Bell Pepper',
  'Beetroot',
  'Pigweed',
  'Cabbage',
  'Bamboo Shoot',
  'Baby Corn',
  'Avocado',
  'Eggplant',
  'Asparagus',
  'Ash Gourd',
  'Artichoke',
  'Colocasia',
  'Potatoes',
  'Ginger'
]

const meats = [
  'Beef',
  'Grass Fed Chicken',
  'Free Range Chicken',
  'Organic Chicken',
  'Turkey',
  'Skinned Chicken',
  'Pork',
  'Partridge',
  'Meat Stock',
  'Keema',
  'Mutton Liver',
  'Ham',
  'Kidney Meat',
  'Crab',
  'Chicken Stock',
  'Chicken Liver',
  'Chicken',
  'Chops',
  'Lamb Meat',
  'Quail',
  'Mutton',
  'Bacon',
  'Shrimp',
  'Tuna Fish',
  'Shellfish',
  'Shark',
  'Hilsa',
  'Sardines',
  'Salmon',
  'Prawns',
  'Pomfret',
  'Perch',
  'Pearl spot',
  'Mussels',
  'Mullet',
  'Squids',
  'Haddock',
  'Flounder',
  'Fish Stock',
  'Fish',
  'Cod',
  'Anchovies',
  'Clams',
  'Cuttle fish',
  'Mackerel',
  'Cat fish',
]

const dairy = [
  'Gruyere Cheese',
  'Gouda Cheese',
  'Feta Cheese',
  'Milk',
  'Brie Cheese',
  'Cream Cheese',
  'Ricotta Cheese',
  'Parmesan Cheese',
  'Blue Cheese',
  'Cheddar Cheese',
  'Mascarpone Cheese',
  'Cream',
  'Provolone Cheese',
  'Mozzarella Cheese',
  'Khoya',
  'Hung Curd',
  'Yogurt',
  'Cottage Cheese',
  'Butter',
  'Buttermilk',
  'Condensed Milk',
  'Clarified Butter',
]

const fruit = [
  'Cranberry',
  'Kiwi',
  'Blueberries',
  'Mango',
  'Watermelon',
  'Tomato',
  'Strawberry',
  'Water Chestnut',
  'Papaya',
  'Orange Rind',
  'Orange',
  'Olives',
  'Pear',
  'Sultana',
  'Mulberry',
  'Lychee',
  'Lemon Juice',
  'Lemon Rind',
  'Lemon',
  'Raisins',
  'Jamun',
  'Tamarind',
  'Grapefruit',
  'Indian Gooseberry',
  'Dried Fruit',
  'Dates',
  'Custard Apple',
  'Currant',
  'Cooking Apples',
  'Coconut',
  'Cherry',
  'Cape Gooseberry',
  'Banana',
  'Peach',
  'Apricots',
  'Apples',
  'Figs',
  'Grapes',
  'Pomegranate',
  'Pineapple',
  'Guava',
  'Plum',
]

const spices = [
  'Coriander Powder',
  'Chives',
  'Galangal',
  'Tulsi',
  'Sage',
  'Rosemary',
  'Yellow Chillies',
  'Oregano',
  'Nasturtium',
  'Salt',
  'Mustard Powder',
  'Paprika',
  'Mint Leaves',
  'Marjoram',
  'Lemongrass',
  'Red Chilli',
  'Saffron',
  'Dried Fenugreek Leaves',
  'Kashmiri Mirch',
  'Onion Seeds',
  'Mace',
  'Nutmeg',
  'Herbs',
  'Thyme',
  'Turmeric',
  'Garam Masala',
  'Five Spice Powder',
  'Fenugreek Seeds',
  'Fennel',
  'Green Cardamom',
  'Dry Ginger Powder',
  'Dill',
  'Curry Leaves',
  'Cumin Seeds',
  'Coriander Seeds',
  'Coriander Leaves',
  'Cloves',
  'Cinnamon',
  'Star Anise',
  'Cayenne',
  'Caraway Seeds',
  'Cajun Spices',
  'Rock Salt',
  'Black Pepper',
  'Black Cumin',
  'Bay Leaf',
  'Basil',
  'Black Cardamom',
  'Asafoetida',
  'Aniseed',
  'Raw Mango Powder',
  'Allspice',
  'Carom Seeds',
  'Parsley',
  'Acacia',
  'Carom Seeds',
  'Parsley',
  'Acacia',
  'Sugar',
  'Brown Sugar',
  'Honey',
  'Golden Syrup',
  'Caramel',
]

const other = [
  'Amaranth',
  'Flour',
  'Muesli',
  'Oats',
  'Jowar',
  'Brown Rice',
  'Arborio Rice',
  'Water Chestnut flour',
  'Barnyard Millet',
  'Tapioca',
  'Semolina',
  'Finger Millet',
  'Puffed Rice',
  'Buckwheat',
  'Kidney Beans',
  'Whole Bengal Gram',
  'Green Gram',
  'All Purpose Flour',
  'Whole Brown Lentils',
  'Husked Black Gram',
  'Husked Green Gram',
  'Couscous',
  'Cornmeal',
  'Pressed Rice',
  'Rice',
  'Breadcrumbs',
  'Bread',
  'Black-eyed Beans',
  'Black Gram',
  'Black Beans',
  'Gram flour',
  'Bengal Gram (Split)',
  'Chickpeas',
  'Basmati Rice',
  'Barley',
  'Pearl Millet',
  'Whole Wheat Flour',
  'Pigeon Pea',
  'Bean Sprouts',
  'Almond Milk',
  'Red Wine Vinegar',
  'Red Wine',
  'Margarine',
  'Soy Milk',
  'White Wine',
  'Yeast',
  'White Pepper',
  'Rice Vinegar',
  'Sea Salt',
  'Hoisin Sauce',
  'Malt Vinegar',
  'Chocolate Chips',
  'Quinoa',
  'Rice Flour',
  'Polenta',
  'Oyster Sauce',
  'Guchchi',
  'Flat Noodles',
  'Balsamic Vinegar',
  'Coconut Oil',
  'Barfi',
  'Rice Noodles',
  'Coffee',
  'Beer',
  'Chocolate',
  'Sake',
  'Vinaigrette',
  'Vanilla Essence',
  'Tortilla',
  'Tomato Puree',
  'Vegetable Oil',
  'Tartaric Acid',
  'Soya Sauce',
  'Vinegar',
  'Sharbat',
  'Vermicelli',
  'Sev',
  'Rum',
  'Roux',
  'Petha',
  'Pasta',
  'Papad',
  'Paan',
  'Meringue',
  'Mayonnaise',
  'Melon Seeds',
  'Lotus Seeds',
  'Vetiver',
  'Screw Pine',
  'Jus',
  'Jelly',
  'Rose Water',
  'Gold Leaves',
  'Glycerine',
  'Gelatin',
  'Fish Sauce',
  'Desiccated Coconut',
  'Cranberry Sauce',
  'Cornflour',
  'Cognac',
  'Coconut Water',
  'Coconut Milk',
  'Cocoa',
  'Tea',
  'Brown Sauce',
  'Baking Soda',
  'Tofu',
  'Baking Powder',
  'Arrowroot',
  'Egg',
  'Alum',
  'Marzipan',
  'Agar',
]

//or faker.internet.username()
const chefs = [
  Enid35,
  Kristian_Murazik,
  Elvis_Kihn,
  Graham.Steuber55,
  Ted_Satterfield31,
  Tyree.Roob,
  Derrick.Marquardt89,
  Terrance_Lesch8,
  Dion_Aufderhar,
  Doris.Macejkovic,
  Leann.Rau,
  Jaeden.Parisian6,
  Josianne.Dach49,
  Mackenzie_Maggio,
  Claudie_Grimes,
  Moses.Abbott,
  Hector.Langworth,
  Miller_Abbott33,
  Darrin_Greenholt65,
  Amos.Kshlerin,
  Vilma_Corkery35,
  Kennedi32,
  Cora.Murazik50,
  Dedric.Goodwin,
  Bessie_Prosacco55,
  Chad_Torp,
  Roselyn.Mraz,
  Marcos_Mueller75,
  Vincenzo.Brown83,
  Eveline51,
  Claude_Buckridge90,
  Heath72,
  Kaycee.Torphy76,
  Xavier63,
  Clementina.Swift86,
  Makenna19,
  Cecil_Stamm,
  Seth_Mraz,
  Malika_Block22,
  Abner29,
  Emmanuel_Cormier,
  Myra_Gottlieb22,
  Kirk.Kilback90,
  Kamron.Funk8,
  Lyla75,
  Amir_Wintheiser,
  Carolina_Wiegand,
  Kip43
]

