const names = [
  'Ralphs',
  'Vons',
  'Trader Joe\'s',
  'Sprouts',
  'Superior Grocers',
  'Northgate Market',
  'Pavilions',
  'Whole Foods Market',
  'Gelson\'s',
  'Smart & Final Extra!',
  'Bristol Farms',
  'Ranch 99',
  'Alberstons',
  'Element 29 Deli',
  'Culver City Farmers Market',
  'Playa Vista Farmers Market',
  'Westchester Market',
  'Inglewood Market',
  'Fresh \'n Easy',
  'Mini Mart Grocery',
  'Handy Mart',
  'Kelso Ranch Market',
  'Kavita Grocery',
  'Berkeley Bowl',
  'Mena Mini Market',
  'Ralphs',
  'Vons',
  'Trader Joe\'s',
  'Sprouts',
  'Superior Grocers',
  'Northgate Market',
  'Pavilions',
  'Whole Foods Market',
  'Gelson\'s',
  'Smart & Final Extra!',
  'Bristol Farms',
  'Ranch 99',
  'Alberstons',
  'Element 29 Deli',
  'Culver City Farmers Market',
  'Playa Vista Farmers Market',
  'Westchester Market',
  'Inglewood Market',
  'Fresh \'n Easy',
  'Mini Mart Grocery',
  'Handy Mart',
  'Kelso Ranch Market',
  'Kavita Grocery',
  'Berkeley Bowl',
  'Mena Mini Market',
  'Ralphs',
  'Vons',
  'Trader Joe\'s',
  'Sprouts',
  'Superior Grocers',
  'Northgate Market',
  'Pavilions',
  'Whole Foods Market',
  'Gelson\'s',
  'Smart & Final Extra!',
  'Bristol Farms',
  'Ranch 99',
  'Alberstons',
  'Element 29 Deli',
  'Culver City Farmers Market',
  'Playa Vista Farmers Market',
  'Westchester Market',
  'Inglewood Market',
  'Fresh \'n Easy',
  'Mini Mart Grocery',
  'Handy Mart',
  'Kelso Ranch Market',
  'Kavita Grocery',
  'Berkeley Bowl',
  'Mena Mini Market',
  'Ralphs',
  'Vons',
  'Trader Joe\'s',
  'Sprouts',
  'Superior Grocers',
  'Northgate Market',
  'Pavilions',
  'Whole Foods Market',
  'Gelson\'s',
  'Smart & Final Extra!',
  'Bristol Farms',
  'Ranch 99',
  'Alberstons',
  'Element 29 Deli',
  'Culver City Farmers Market',
  'Playa Vista Farmers Market',
  'Westchester Market',
  'Inglewood Market',
  'Fresh \'n Easy',
  'Mini Mart Grocery',
  'Handy Mart',
  'Kelso Ranch Market',
  'Kavita Grocery',
  'Berkeley Bowl',
  'Mena Mini Market'
]

const allIngredients = [
  'arugula',
  'beet greens',
  'chiles',
  'fennel',
  'fresh mint leaves',
  'garlic',
  'lemongrass',
  'low sodium soy sauce',
  'mushrooms',
  'parsley',
  'red miso',
  'salt',
  'shallots',
  'tofu',
  'vegetable broth',
  'chicken breasts',
  'chicken broth',
  'chili powder',
  'colby jack cheese',
  'cream',
  'frozen corn',
  'garlic cloves',
  'ground cumin',
  'ground pepper',
  'onion',
  'red enchilada sauce',
  'tomato soup',
  'tortilla chips',
  'velveeta cheese',
  'agave nectar',
  'almond butter',
  'carrots',
  'fresh cilantro',
  'lime juice',
  'raisins',
  'red bell pepper',
  'red pepper flakes',
  'tamari',
  'black pepper',
  'cooked bacon',
  'eggs',
  'milk',
  'refrigerated pie crust',
  'salt',
  'sharp cheddar cheese',
  'coffee',
  'ice',
  'liquid stevia',
  'vanilla extract',
  'whey protein powder',
  'lemon pie filling',
  'baking powder',
  'confectioners\' sugar',
  'cornstarch',
  'cream cheese',
  'eggs',
  'flour',
  'granulated sugar',
  'lemon juice',
  'salt',
  'salt',
  'unsalted butter',
  'vanilla extract',
  'whole milk',
  'cocoa powder',
  'coconut oil',
  'maple syrup',
  'peanut butter',
  'blueberries',
  'butter',
  'cream cheese',
  'eggs',
  'maple syrup',
  'milk',
  'white bread',
  'chicken stock',
  'cooked linguine',
  'dijon mustard',
  'extra virgin olive oil',
  'feta cheese',
  'garlic',
  'garlic cloves',
  'greek olives',
  'juice of lemon',
  'marinated artichoke hearts',
  'oregano',
  'skinless boneless chicken breasts',
  'sundried tomatoes',
  'asparagus spears',
  'bacon',
  'eggs',
  'sea-salt',
  'bread crumbs',
  'fresh basil',
  'fresh mozzarella cheese',
  'olive oil',
  'parmesan cheese',
  'salt and pepper',
  'skinless boneless chicken breasts',
  'tomatoes',
  'apple cider vinegar',
  'boneless chicken thighs',
  'coconut aminos',
  'dates',
  'garlic powder',
  'ginger',
  'green onion',
  'mixed greens',
  'rice',
  'sesame seeds',
  'tapioca starch',
  'water',
  'baking soda',
  'Biscoff spread',
  'brown sugar',
  'butter',
  'cashews',
  'flour',
  'salt',
  'vanilla',
  'white chocolate chips',
  'white sugar',
  'whole eggs',
  'celery',
  'cooked bacon',
  'dijon mustard',
  'green onions',
  'hardboiled eggs',
  'mayonnaise',
  'milk',
  'onion',
  'bell pepper',
  'salt',
  'sugar',
  'vinegar',
  'yukon gold potatoes',
  'dark chocolate bar',
  'silken tofu',
  'orange juice',
  'unsweetened cocoa powder',
  'agave nectar',
  'ground cardamom',
  'orange zest',
  'baking powder',
  'baking soda',
  'butter',
  'cinnamon',
  'cream cheese',
  'eggs',
  'milk',
  'nuts',
  'oil',
  'powdered sugar',
  'pumpkin pie filling',
  'salt',
  'sugar',
  'unbleached flour',
  'vanilla',
  'capers',
  'cornstarch',
  'fresh flat-leaf parsley',
  'garlic',
  'kosher salt',
  'lemon juice',
  'lemon zest',
  'low sodium chicken broth',
  'sea scallops',
  'unsalted butter',
  'candy canes',
  'peppermint baking chips',
  'peppermint extract',
  'sweetened condensed milk',
  'bell pepper',
  'garlic',
  'grape tomatoes',
  'green beans',
  'kosher salt',
  'olive oil',
  'parmesan cheese',
  'celery hearts',
  'garlic',
  'olive oil',
  'orange zest',
  'parsley',
  'pomegranate arils',
  'pomegranate juice',
  'salt',
  'shells',
  'sweet onion',
  'wild rice',
  'avocados',
  'ground pepper',
  'kosher salt',
  'lime juice',
  'olive oil',
  'roasted pork',
  'sour cream',
  'tortilla chips',
  'agave nectar',
  'almond butter',
  'cinnamon',
  'eggs',
  'ground nutmeg',
  'orange juice',
  'orange zest',
  'pears',
  'salt',
  'vanilla beans',
  'beef',
  'green onions',
  'lime',
  'orange',
  'soy sauce',
  'presley',
  'bacon',
  'balsamic vinegar',
  'canned tomatoes',
  'chicken stock',
  'chile flakes',
  'fresh parsley',
  'fresh sage',
  'garlic cloves',
  'great northern beans',
  'honey',
  'olive oil',
  'onion',
  'salt',
  'tomato paste',
  'baking soda',
  'blueberries',
  'brown sugar',
  'egg',
  'graham cracker crumbs',
  'granulated sugar',
  'ground cinnamon',
  'salt',
  'sour cream',
  'unbleached all purpose flour',
  'unsalted butter',
  'vanilla extract',
  'almond milk',
  'chia seeds',
  'cinnamon',
  'ground ginger',
  'maple syrup',
  'nonfat greek yogurt',
  'nutmeg',
  'old fashioned oats',
  'pumpkin puree',
  'vanilla extract',
  'bone-in skin-on chicken thighs',
  'buttermilk',
  'chili powder',
  'cumin',
  'fresh cilantro leaves',
  'garlic powder',
  'kosher salt',
  'onion powder',
  'oregano',
  'smoked paprika',
  'unsalted butter',
  'bell pepper',
  'canola oil',
  'carrot',
  'chicken',
  'chili',
  'eggs',
  'garlic',
  'ginger',
  'kosher salt',
  'onion',
  'oyster sauce',
  'peas',
  'rice',
  'scallions',
  'sesame oil',
  'sesame seeds',
  'soy sauce',
  'bulk pork sausage',
  'carrots',
  'onion',
  'pepper',
  'potatoes',
  'salt',
  'stewed tomatoes',
  'turnip',
  'water',
  'cream cheese',
  'egg yolks',
  'eggs',
  'graham cracker crumbs',
  'lemon juice',
  'lemon zest',
  'salt',
  'sour cream',
  'sugar',
  'unsalted butter',
  'vanilla',
  'brown sugar',
  'chicken broth',
  'cooked rice',
  'dried parsley flakes',
  'garlic clove',
  'ground ginger',
  'low sodium soy sauce',
  'oregano',
  'skinless boneless chicken breast halves',
  'water',
  'extra virgin olive oil',
  'flat-leaf parsley',
  'garlic cloves',
  'ground pepper',
  'potatoes',
  'red pepper flakes',
  'red wine vinegar',
  'salt',
  'skinless boneless chicken thighs',
  'water',
  'almond flour',
  'baking powder',
  'banana',
  'blueberries',
  'coconut milk',
  'coconut oil',
  'eggs',
  'peanut butter',
  'salt',
  'vanilla extract',
  'walnuts',
  'yogurt',
  'champagne',
  'juice',
  'cream',
  'chocolate chip cookies',
  'cream cheese',
  'egg',
  'sugar',
  'vanilla',
  'cranberry juice',
  'lime juice',
  'simple syrup',
  'triple sec',
  'pisco',
  'baking powder',
  'baking soda',
  'blueberries',
  'canola oil',
  'egg substitute',
  'non-fat milk',
  'salt',
  'sugar',
  'turbinado sugar',
  'unsalted butter',
  'vanilla extract',
  'whole wheat pastry flour',
  'baking soda',
  'dutch processed cocoa',
  'eggs',
  'flour',
  'granulated sugar',
  'light brown sugar',
  'peppermint patties',
  'powdered sugar',
  'unsalted butter',
  'vanilla extract',
  'balsamic vinegar',
  'basil leaves',
  'breadcrumbs',
  'canned tomatoes',
  'dry white wine',
  'eggs',
  'garlic',
  'kosher salt',
  'olive oil',
  'olive oil',
  'parmesan cheese',
  'parmesan cheese',
  'pepperoni',
  'shredded mozzarella',
  'tomato paste',
  'yellow onion',
  'chocolate syrup',
  'eggnog',
  'milk',
  'peppermint extract',
  'vanilla extract',
  'bread crumbs',
  'butter',
  'cream of chicken soup',
  'onion',
  'potatoes',
  'salt and pepper',
  'shredded cheddar cheese',
  'sour cream',
  'cinnamon',
  'egg white',
  'ginger',
  'granulated sugar',
  'light brown sugar',
  'nutmeg',
  'raw pepitas',
  'salt',
  'water',
  'canned pumpkin puree',
  'espresso',
  'ground cinnamon',
  'milk',
  'pumpkin pie spice',
  'sugar',
  'vanilla extract',
  'whipped cream',
  'butter',
  'olive oil',
  'onions',
  'canned beef broth',
  'marsala wine',
  'dried thyme',
  'salt and pepper',
  'sugar',
  'texas toast',
  'provolone cheese',
  'swiss cheese',
  'parmesan cheese',
  'balsamic vinegar',
  'balsamic vinegar',
  'chicken stock',
  'Cos lettuce',
  'duck breast',
  'garlic powder',
  'grape tomatoes',
  'juice of lemon',
  'kalamata olives',
  'olive oil',
  'olive oil',
  'parsley',
  'quinoa',
  'red onion',
  'reduced fat cheese',
  'salt',
  'stock powder',
  'cherry preserves',
  'dried bing cherries',
  'red wine vinegar',
  'cocoa',
  'coconut water',
  'dates',
  'ice',
  'raspberries',
  'raw cashews',
  'romaine',
  'salt',
  'vanilla extract',
  'all purpose flour',
  'baking powder',
  'baking soda',
  'bananas',
  'butter',
  'butter',
  'eggs',
  'granulated sugar',
  'irish cream',
  'salt',
  'semi sweet chocolate chips',
  'semi sweet chocolate chips',
  'sugar',
  'vanilla',
  'vanilla',
  'butter',
  'cooked chicken',
  'hot sauce',
  'kosher salt',
  'olive oil',
  'potatoes',
  'ranch dressing',
  'scallions',
  'shredded cheddar cheese',
  'baking powder',
  'baking soda',
  'cane sugar',
  'coconut coffee creamer',
  'coconut milk beverage',
  'dairy free margarine',
  'gluten free flour blend',
  'powdered sugar',
  'salt',
  'shortening',
  'flax seed oil',
  'vanilla extract',
  'water',
  'white vinegar',
  'baking soda',
  'brown sugar',
  'butter',
  'chocolate chips',
  'Chocolate Easter Eggs',
  'eggs',
  'flour',
  'instant vanilla pudding',
  'salt',
  'sprinkles',
  'sugar',
  'vanilla extract',
  'white chocolate chips',
  'canned chickpeas',
  'cocoa powder',
  'maple syrup',
  'peanut butter',
  'peanut butter cups',
  'vanilla',
  'butter',
  'chia seeds',
  'dried cranberries',
  'honey',
  'rolled oats',
  'unsalted pistachios',
  'vanilla extract',
  'butter',
  'green onions',
  'milk',
  'shredded cheddar cheese',
  'mix',
  'bananas',
  'cinnamon',
  'coconut flakes',
  'fresh mint',
  'juice of lime',
  'kiwis',
  'mango',
  'mangos',
  'pineapple',
  'red grapes',
  'strawberries',
  'butter',
  'halibut',
  'lemon pepper',
  'pretzel rods',
  'salt',
  'walnuts',
  'canned tomatoes',
  'corn kernels',
  'cumin',
  'fresh cilantro',
  'garlic cloves',
  'low fat shredded cheddar cheese',
  'low fat sour cream',
  'low sodium chicken broth',
  'olive oil',
  'pinto beans',
  'quinoa',
  'salt',
  'breadcrumbs',
  'buttermilk biscuits',
  'carrots',
  'garlic cloves',
  'ground pork',
  'lean ground beef',
  'marinara sauce',
  'meatballs',
  'oil',
  'parmesan',
  'parsley',
  'Salt & Pepper',
  'shredded cheddar cheese',
  'graham crackers',
  'pumpkin pie spice',
  'pumpkin puree',
  'skim vanilla greek yogurt',
  'baking soda',
  'butter',
  'chocolate chips',
  'crunchy peanut butter',
  'eggs',
  'granulated sugar',
  'light brown sugar',
  'm&ms',
  'raisins',
  'rolled oats',
  'salt',
  'vanilla extract',
  'baking soda',
  'bell pepper',
  'cod',
  'dried chickpeas',
  'extra virgin olive oil',
  'garlic',
  'rosemary',
  'salt',
  'bell peppers',
  'dry breadcrumbs',
  'egg',
  'fresh parsley',
  'fresh rosemary',
  'ground pepper',
  'italian sausages',
  'red onion',
  'salt',
  'zucchini',
  'barley',
  'black beans',
  'celery stalks',
  'cherry tomatoes',
  'cilantro',
  'garlic clove',
  'juice of lemon',
  'olive oil',
  'radishes',
  'salt and pepper',
  'scallions',
  'avocado',
  'garlic',
  'habanero chile',
  'onion',
  'salt',
  'tomatillo',
  'heavy whipping cream',
  'semi sweet chocolate chips',
  'butter',
  'semi sweet chocolate chips',
  'butter',
  'sugar',
  'whole eggs',
  'egg yolks',
  'vanilla extract',
  'salt',
  'flour',
  'ice cream',
  'chocolate syrup',
  'whipped cream',
  'berries',
  'gruyere cheese',
  'prosciutto',
  'unsalted butter',
  'white bread',
  'carrots',
  'cauliflower',
  'dried parsley',
  'dried rosemary',
  'garlic',
  'kale',
  'olive oil',
  'vegetable stock',
  'yellow onion',
  'bittersweet chocolate',
  'heavy whipping cream',
  'maple flavoring',
  'unsalted butter',
  'vanilla',
  'cinnamon',
  'coconut oil',
  'dried cranberries',
  'granulated sugar',
  'maple syrup',
  'old fashioned rolled oats',
  'orange zest',
  'pecans',
  'sea salt',
  'anchovy',
  'beef tenderloin',
  'capers',
  'crostini',
  'dijon mustard',
  'egg',
  'fresh flat-leaf parsley',
  'garlic cloves',
  'kosher salt',
  'olive oil',
  'orange zest',
  'shallots',
  'truffle oil',
  'worcestershire sauce',
  'canned coconut milk',
  'chicken',
  'chicken bouillon',
  'cilantro',
  'cumin powder',
  'garlic clove',
  'onion',
  'red bell pepper',
  'salt and pepper',
  'tomato paste',
  'vegetable oil',
  'white rice',
  'canned tomato sauce',
  'cheese tortellini',
  'flour',
  'garlic',
  'heavy cream',
  'olive oil',
  'onion',
  'pimenton de la vera',
  'salt and pepper',
  'vegetable broth',
  'baking powder',
  'baking soda',
  'egg',
  'flour',
  'granulated sugar',
  'sesame seeds',
  'vegetable oil',
  'water',
  'all purpose flour',
  'apples',
  'baking powder',
  'brown sugar',
  'cinnamon',
  'eggs',
  'salt',
  'slivered almonds',
  'vanilla extract',
  'white sugar',
  'black pepper',
  'brown sugar',
  'chicken wings',
  'cumin',
  'garlic powder',
  'kosher salt',
  'mustard powder',
  'onion powder',
  'paprika',
  'corn syrup',
  'eggs',
  'margarine',
  'pecans',
  'salt',
  'unsweetened cocoa powder',
  'vanilla extract',
  'white sugar',
  'food dye',
  'maple syrup',
  'milk',
  'raw sunflower seeds',
  'water',
  'funnel',
  'basil',
  'bell pepper',
  'chives',
  'extra virgin olive oil',
  'lemon',
  'lemon balm',
  'sea bass',
  'sea salt',
  'egg whites',
  'eggs',
  'feta cheese',
  'flat-leaf parsley',
  'ground pepper',
  'olive oil',
  'onion',
  'salt',
  'water',
  'zucchini',
  'chicken broth',
  'dandelion greens',
  'onion',
  'pancetta',
  'red pepper flakes',
  'salt',
  'sugar',
  'butter',
  'egg whites',
  'gelatin',
  'heavy whipping cream',
  'limes',
  'shortbread cookies',
  'sugar',
  'water',
  'almond milk',
  'baking powder',
  'cream cheese',
  'flour',
  'graham cracker crumbs',
  'oat bran',
  'rolled oats',
  'salt',
  'strawberries',
  'sukrin sweetener',
  'vanilla extract',
  'corn syrup',
  'cream of tartar',
  'egg white',
  'egg yolk',
  'flour',
  'granulated sugar',
  'half n half',
  'light brown sugar',
  'old-fashioned oats',
  'sea salt',
  'sorbet',
  'unsalted butter',
  'vanilla bean',
  'vanilla extract',
  'water',
  'whole wheat flour',
  'canned black beans',
  'cayenne pepper',
  'chili powder',
  'egg roll wrappers',
  'frozen corn',
  'green chiles',
  'green onions',
  'ground cumin',
  'pepper',
  'salt',
  'shredded cheese',
  'spinach',
  'carrots',
  'cumin seed',
  'curry leaves',
  'fresh cilantro leaves',
  'fresh peas',
  'garlic cloves',
  'ginger',
  'green chiles',
  'green onions',
  'ground pepper',
  'turmeric',
  'mustard seed',
  'vegetable oil',
  'whole coriander seed',
  'food coloring gel',
  'frosting',
  'lb cake',
  'marshmallows',
  'skittles',
  'baking powder',
  'coarse salt',
  'creamy peanut butter',
  'eggs',
  'flour',
  'jam',
  'light brown sugar',
  'roasted peanuts',
  'salt',
  'unsalted butter',
  'vanilla extract',
  'bell pepper',
  'butter',
  'cayenne pepper',
  'eggs',
  'flour',
  'flour',
  'kosher salt',
  'paprika',
  'potatoes',
  'seasoned salt',
  'seasoned salt',
  'steak',
  'vegetable oil',
  'whole milk',
  'whole milk',
  'arugula',
  'fennel bulb',
  'garlic cloves',
  'golden brown sugar',
  'olive oil',
  'onion',
  'pumpkin pie mix',
  'red pepper flakes',
  'rigatoni',
  'water',
  'black pepper',
  'egg',
  'garlic clove',
  'bbq sauce',
  'italian seasoning',
  'pasta shells',
  'parsley',
  'salt',
  'shredded mozzarella',
  'shredded mozzarella cheese',
  'skim milk ricotta',
  'spinach',
  'baking powder',
  'blueberries',
  'butter',
  'egg',
  'milk',
  'salt',
  'sugar',
  'sweetened coconut',
  'vanilla extract',
  'white flour',
  'whole wheat flour',
  'cilantro leaves',
  'coriander powder',
  'cumin seeds',
  'garam masala',
  'ghee',
  'ginger',
  'green chili',
  'onion',
  'paneer',
  'rajma masala',
  'red chili powder',
  'salt',
  'tomato',
  'turmeric powder',
  'water',
  'mutter',
  'brussels sprouts',
  'coconut',
  'coconut oil',
  'lite coconut milk',
  'nutmeg',
  'pepper',
  'salt',
  'butter',
  'cinnamon',
  'cream cheese',
  'eggs',
  'granulated sugar',
  'juice of lemon',
  'lemon zest',
  'milk',
  'strawberries',
  'vanilla',
  'white sandwich bread',
  'almond',
  'baking powder',
  'banana',
  'blueberries',
  'cinnamon',
  'coconut flakes',
  'coconut oil',
  'coconut sugar',
  'ground flaxseed',
  'hemp seeds',
  'maple syrup',
  'rolled oats',
  'sea salt',
  'slivered almonds',
  'strawberries',
  'blueberries',
  'blueberries',
  'cream cheese',
  'graham cracker crumbs',
  'granulated sugar',
  'lemon juice',
  'strawberries',
  'sweetened condensed milk',
  'unsalted butter',
  'vanilla extract',
  'apple cider vinegar',
  'cabbage',
  'carrots',
  'dijon mustard',
  'fat free greek yogurt',
  'garlic',
  'Salt & Pepper',
  'scallions',
  'sugar',
  'butter',
  'egg yolks',
  'eggs',
  'flour',
  'instant coffee granules',
  'mint',
  'raspberry jam',
  'semisweet chocolate',
  'sugar',
  'vanilla extract',
  'broth',
  'chili paste',
  'cognac',
  'dried tarragon',
  'ears corn',
  'fingerling potatoes',
  'flat-leaf parsley',
  'heavy cream',
  'herbes de provence',
  'lobsters',
  'olive oil',
  'onion',
  'potato starch',
  'salt & pepper',
  'tomato juice',
  'unsalted butter',
  'water',
  'white wine',
  'coffee liqueur',
  'corn syrup',
  'eggs',
  'flour',
  'salt',
  'semisweet chocolate chips',
  'sugar',
  'unsalted butter',
  'vanilla extract',
];

const setObj = new Set(allIngredients)
const ingredients = [...setObj]

const getRand = (min, max) => Math.random() * (max - min) + min;

const storeSeedGen = () => {
  let output = [], i, j, k;
  for (i = 0; i < 100; i++) {
    const id = i + 1;
    const name = names[i];
    const latitude = getRand(34.035497, 33.961364);
    const longitude = getRand(-118.458218, -118.299864);
    const score = Math.floor(getRand(4, 10));
    const ingrLen = Math.floor(getRand(30, 50));
    let ingrName;
    let arr = [];
    for (j = 0; j < ingrLen; j++) {
      ingrName = ingredients[Math.floor(getRand(0, 100))]
      arr.push(ingrName);
    }
    const subObj = new Set(arr);
    let subArr = [...subObj];
    let storeIngr = [];
    let item;
    for (k = 0; k < subArr.length; k++) {
      item = {
        name: subArr[k].toLowerCase(), 
        price: getRand(0.99, 15).toFixed(2)
      }
      storeIngr.push(item);
    }


    const store = {
      id,
      name,
      latitude,
      longitude,
      score,
      ingredients: storeIngr
    };
    output.push(store)
  }
  return output;
}

const storeSeed = storeSeedGen();

module.exports = storeSeed;
